# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'handset1.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(350, 558)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.BENTER = QtGui.QPushButton(self.dockWidgetContents)
        self.BENTER.setGeometry(QtCore.QRect(30, 60, 91, 41))
        self.BENTER.setObjectName(_fromUtf8("BENTER"))
        self.L8 = QtGui.QRadioButton(self.dockWidgetContents)
        self.L8.setGeometry(QtCore.QRect(20, 250, 117, 22))
        self.L8.setObjectName(_fromUtf8("L8"))
        self.BMODE = QtGui.QPushButton(self.dockWidgetContents)
        self.BMODE.setGeometry(QtCore.QRect(130, 60, 91, 41))
        self.BMODE.setObjectName(_fromUtf8("BMODE"))
        self.BGOTO = QtGui.QPushButton(self.dockWidgetContents)
        self.BGOTO.setGeometry(QtCore.QRect(230, 60, 91, 41))
        self.BGOTO.setObjectName(_fromUtf8("BGOTO"))
        self.BN = QtGui.QPushButton(self.dockWidgetContents)
        self.BN.setGeometry(QtCore.QRect(130, 110, 91, 41))
        self.BN.setObjectName(_fromUtf8("BN"))
        self.BE = QtGui.QPushButton(self.dockWidgetContents)
        self.BE.setGeometry(QtCore.QRect(230, 130, 91, 41))
        self.BE.setObjectName(_fromUtf8("BE"))
        self.BE_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.BE_2.setGeometry(QtCore.QRect(30, 130, 91, 41))
        self.BE_2.setObjectName(_fromUtf8("BE_2"))
        self.BS = QtGui.QPushButton(self.dockWidgetContents)
        self.BS.setGeometry(QtCore.QRect(130, 160, 91, 41))
        self.BS.setObjectName(_fromUtf8("BS"))
        self.B7 = QtGui.QPushButton(self.dockWidgetContents)
        self.B7.setGeometry(QtCore.QRect(80, 240, 51, 41))
        self.B7.setObjectName(_fromUtf8("B7"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(80, 220, 51, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(150, 220, 51, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.B8 = QtGui.QPushButton(self.dockWidgetContents)
        self.B8.setGeometry(QtCore.QRect(150, 240, 51, 41))
        self.B8.setObjectName(_fromUtf8("B8"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(220, 220, 51, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.B9 = QtGui.QPushButton(self.dockWidgetContents)
        self.B9.setGeometry(QtCore.QRect(220, 240, 51, 41))
        self.B9.setObjectName(_fromUtf8("B9"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(220, 290, 51, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.B5 = QtGui.QPushButton(self.dockWidgetContents)
        self.B5.setGeometry(QtCore.QRect(150, 310, 51, 41))
        self.B5.setObjectName(_fromUtf8("B5"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(150, 290, 51, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.B6 = QtGui.QPushButton(self.dockWidgetContents)
        self.B6.setGeometry(QtCore.QRect(220, 310, 51, 41))
        self.B6.setObjectName(_fromUtf8("B6"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(80, 290, 51, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.B10 = QtGui.QPushButton(self.dockWidgetContents)
        self.B10.setGeometry(QtCore.QRect(80, 310, 51, 41))
        self.B10.setObjectName(_fromUtf8("B10"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(220, 360, 51, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.B2 = QtGui.QPushButton(self.dockWidgetContents)
        self.B2.setGeometry(QtCore.QRect(150, 380, 51, 41))
        self.B2.setObjectName(_fromUtf8("B2"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(150, 360, 51, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.B3 = QtGui.QPushButton(self.dockWidgetContents)
        self.B3.setGeometry(QtCore.QRect(220, 380, 51, 41))
        self.B3.setObjectName(_fromUtf8("B3"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(80, 360, 51, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.B1 = QtGui.QPushButton(self.dockWidgetContents)
        self.B1.setGeometry(QtCore.QRect(80, 380, 51, 41))
        self.B1.setObjectName(_fromUtf8("B1"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(220, 430, 51, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.BUP = QtGui.QPushButton(self.dockWidgetContents)
        self.BUP.setGeometry(QtCore.QRect(150, 450, 51, 41))
        self.BUP.setObjectName(_fromUtf8("BUP"))
        self.label_11 = QtGui.QLabel(self.dockWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(150, 430, 51, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.BDOWN = QtGui.QPushButton(self.dockWidgetContents)
        self.BDOWN.setGeometry(QtCore.QRect(220, 450, 51, 41))
        self.BDOWN.setObjectName(_fromUtf8("BDOWN"))
        self.label_12 = QtGui.QLabel(self.dockWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(80, 430, 51, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.B0 = QtGui.QPushButton(self.dockWidgetContents)
        self.B0.setGeometry(QtCore.QRect(80, 450, 51, 41))
        self.B0.setObjectName(_fromUtf8("B0"))
        self.L4 = QtGui.QRadioButton(self.dockWidgetContents)
        self.L4.setGeometry(QtCore.QRect(20, 320, 117, 22))
        self.L4.setObjectName(_fromUtf8("L4"))
        self.L2 = QtGui.QRadioButton(self.dockWidgetContents)
        self.L2.setGeometry(QtCore.QRect(20, 390, 117, 22))
        self.L2.setObjectName(_fromUtf8("L2"))
        self.L1 = QtGui.QRadioButton(self.dockWidgetContents)
        self.L1.setGeometry(QtCore.QRect(20, 460, 117, 22))
        self.L1.setObjectName(_fromUtf8("L1"))
        self.LALT = QtGui.QRadioButton(self.dockWidgetContents)
        self.LALT.setGeometry(QtCore.QRect(240, 190, 117, 22))
        self.LALT.setObjectName(_fromUtf8("LALT"))
        self.DISPLAY = QtGui.QTextBrowser(self.dockWidgetContents)
        self.DISPLAY.setGeometry(QtCore.QRect(30, 0, 291, 51))
        self.DISPLAY.setObjectName(_fromUtf8("DISPLAY"))
        DockWidget.setWidget(self.dockWidgetContents)
	#self.BENTER.clicked.connect(on_N_clicked)
	self.BENTER.pressed.connect(on_N_pressed)
	self.BENTER.released.connect(on_N_released)


        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.BENTER.setText(_translate("DockWidget", "ENTER", None))
        self.L8.setText(_translate("DockWidget", "x8", None))
        self.BMODE.setText(_translate("DockWidget", "MODE", None))
        self.BGOTO.setText(_translate("DockWidget", "GOTO", None))
        self.BN.setText(_translate("DockWidget", "N", None))
        self.BE.setText(_translate("DockWidget", "E", None))
        self.BE_2.setText(_translate("DockWidget", "E", None))
        self.BS.setText(_translate("DockWidget", "S", None))
        self.B7.setText(_translate("DockWidget", "7", None))
        self.label.setText(_translate("DockWidget", "SLEW", None))
        self.label_2.setText(_translate("DockWidget", "RET", None))
        self.B8.setText(_translate("DockWidget", "8", None))
        self.label_3.setText(_translate("DockWidget", "M", None))
        self.B9.setText(_translate("DockWidget", "9", None))
        self.label_4.setText(_translate("DockWidget", "STAR", None))
        self.B5.setText(_translate("DockWidget", "5", None))
        self.label_5.setText(_translate("DockWidget", "FOCUS", None))
        self.B6.setText(_translate("DockWidget", "6", None))
        self.label_6.setText(_translate("DockWidget", "FIND", None))
        self.B10.setText(_translate("DockWidget", "4", None))
        self.label_7.setText(_translate("DockWidget", "CNGC", None))
        self.B2.setText(_translate("DockWidget", "2", None))
        self.label_8.setText(_translate("DockWidget", "MAP", None))
        self.B3.setText(_translate("DockWidget", "3", None))
        self.label_9.setText(_translate("DockWidget", "CNTR", None))
        self.B1.setText(_translate("DockWidget", "1", None))
        self.label_10.setText(_translate("DockWidget", "NEXT", None))
        self.BUP.setText(_translate("DockWidget", "U", None))
        self.label_11.setText(_translate("DockWidget", "PREV", None))
        self.BDOWN.setText(_translate("DockWidget", "D", None))
        self.label_12.setText(_translate("DockWidget", "GUIDE", None))
        self.B0.setText(_translate("DockWidget", "0", None))
        self.L4.setText(_translate("DockWidget", "x4", None))
        self.L2.setText(_translate("DockWidget", "x2", None))
        self.L1.setText(_translate("DockWidget", "x1", None))
        self.LALT.setText(_translate("DockWidget", "ALT", None))

def on_N_pressed():
	ui.DISPLAY.setText('123456789')
def on_N_released():
	ui.DISPLAY.setText('987654321')

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DockWidget = QtGui.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())
    self.BENTER.clicked.connect(on_N_clicked)
